### ISSUE TITLE
main.js:38 Uncaught ReferenceError: timeOut is not defined     at lightOn (main.js:38:6)     at HTMLDocument.<anonymous> (main.js:7:3)

### ISSUE THREAD

**Issue by ccp84** [ccp84/reaction_lights#4]
setTimeout(function() {
	let timeOut = 0;
    timeOut = lightTimer();
    lightOff(activeLight);
  **}, timeOut);**
}

**Comment by ccp84** [comment]
**RESOLVED**
Variable timeOut needs to be declared globally in order to be read outside of the timer function
  let timeOut = 0;
  setTimeout(function() {
    timeOut = lightTimer();
    lightOff(activeLight);
  }, timeOut);
}
